version: "1.0"
info:
  model: int-scaffold
packages:
- name: DigitalCardIssuanceProject
  gitServerName: VikashgithubRepo
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
- name: OnPremCardIssuanceSFDCServices
  gitServerName: VikashgithubRepo
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
- name: WmSalesforceRESTProvider
  gitServerName: VikashgithubRepo
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
- name: customCobrandingService
  gitServerName: VikashgithubRepo
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
